# Generated by Django 5.2.7 on 2025-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_link',
            field=models.URLField(blank=True, help_text="Optional. If provided, a 'View more' button will appear on the category page and open this URL in a new tab.", max_length=600, null=True),
        ),
    ]
